name: Screenshot Gemini

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Gemini 分享链接（https://g.co/gemini/share/xxxx）'
        required: true
        type: string

jobs:
  shot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Run screenshot
        run: node screenshot.js ${{ inputs.url }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: gemini-screenshot
          path: gemini_canvas_*.png

      # 可选：把图片直接提交回仓库
      - name: Commit image back
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gemini_canvas_*.png || true
          git commit -m "Add screenshot" || true
          git push || true
